[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/agent"
  to = "/.netlify/functions/ai-agent"
  status = 200
  force = true

[[redirects]]
  from = "/api/ollama/*"
  to = "/.netlify/functions/ollama"
  status = 200
  force = true

[[redirects]]
  from = "/api/groq/*"
  to = "/.netlify/functions/groq"
  status = 200
  force = true

[[redirects]]
  from = "/api/claude/*"
  to = "/.netlify/functions/claude"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
