[[redirects]]
  from = "/api/groq/*"
  to = "https://api.groq.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/claude/*"
  to = "https://api.anthropic.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
